---
- hosts: all
  become: true
  tasks:
    ## Custom

    - name: 'AWS tasks'
      include_tasks: aws.yml
      args:
        apply:
          tags:
            - aws

    - name: 'Custom scripts'
      include_tasks: scripts.yml
      args:
        apply:
          tags:
            - scripts
            
    - name: 'Auth/SSH'
      include_tasks: auth-ssh.yml
      args:
        apply:
          tags:
            - auth-ssh

    - name: 'Application'
      include_tasks: app.yml
      args:
        apply:
          tags:
            - app
