---
- hosts: all
  become: true
  tasks:
    #####
    # Install and start system services
    - name: 'Install pre-requisite software'
      apt:
        name:
        - 'virtualbox-guest-dkms'
        - 'virtualbox-guest-utils'
        - 'linux-image-extra-virtual'
        - 'virtualbox-guest-x11'
      tags:
        - 'packages'
        - 'apt'

    - name: 'set timezone'
      timezone:
        name: America/New_York
      tags:
        - 'settings'
        - 'tz'
        
    ## Custom

    - name: 'AWS tasks'
      include_tasks: aws.yml
      args:
        apply:
          tags:
            - aws

    - name: 'Custom scripts'
      include_tasks: scripts.yml
      args:
        apply:
          tags:
            - scripts
            
    - name: 'Auth/SSH'
      include_tasks: auth-ssh.yml
      args:
        apply:
          tags:
            - auth-ssh

    - name: 'Application'
      include_tasks: app.yml
      args:
        apply:
          tags:
            - app
